input {
  kafka {
    # Usiamo kafka:29092 perché Logstash è dentro la rete 'tap' di Docker
    bootstrap_servers => "kafka:29092"
    topics => ["city-sensors"]
    codec => "json"
    # Inizia a leggere dall'inizio se il topic è nuovo
    auto_offset_reset => "earliest"
    group_id => "logstash-group"
  }
}

filter {
  # Opzionale: Convertiamo il timestamp in un formato che Elastic apprezza subito
  date {
    match => [ "timestamp", "ISO8601" ]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "smart-city-data-%{+YYYY.MM.dd}"
    # Dato che usi la versione 7.x, non serve specificare user/password 
    # a meno che tu non abbia attivato la sicurezza X-Pack
  }
  
  # Questo ti permette di vedere i dati passare nel terminale con 'docker logs -f logstash'
  stdout { codec => rubydebug }
}
