input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["city-sensors"]
    codec => json
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "smart-city-raw"
  }
  stdout { codec => rubydebug }
}